# Generated by Django 2.0 on 2018-01-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(default='default_description', max_length=250),
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='default_name', max_length=150),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(default='default_type', max_length=50),
        ),
    ]
