# Generated by Django 2.0.1 on 2018-01-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0004_auto_20180116_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resourcePermissions',
        ),
        migrations.AddField(
            model_name='resource',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to='AuthorizationManagement.Owner'),
        ),
        migrations.AddField(
            model_name='resource',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to='AuthorizationManagement.CustomUser'),
        ),
    ]
