# Generated by Django 2.0.1 on 2018-01-16 19:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('AuthorizationManagement', '0005_auto_20180116_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AuthorizationManagement.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthorizationManagement.Owner')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('AuthorizationManagement.owner',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='Resource',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to='AuthorizationManagement.CustomUser'),
        ),
        migrations.AlterField(
            model_name='AccessRequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorizationManagement.CustomUser'),
        ),
        migrations.AlterField(
            model_name='DeletionRequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorizationManagement.CustomUser'),
        ),
        migrations.AlterField(
            model_name='Resource',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to='AuthorizationManagement.Owner'),
        ),
        migrations.AlterField(
            model_name='Resource',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to='AuthorizationManagement.CustomUser'),
        ),
        migrations.AlterField(
            model_name='AccessRequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorizationManagement.CustomUser'),
        ),
        migrations.AlterField(
            model_name='DeletionRequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorizationManagement.CustomUser'),
        ),
        migrations.AlterField(
            model_name='Resource',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to='AuthorizationManagement.Owner'),
        ),
    ]
